# configure updates globally
# default: all
# allowed: all, insecure, False
update: all

# configure dependency pinning globally
# default: True
# allowed: True, False
pin: True
requirements:
  - "requirements.txt"
  - "{{cookiecutter.project_name}}/requirements.txt"
