name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r {{cookiecutter.project_name}}/requirements.txt
#    WIP: vlad doster
#    - name: Create replay project
#      run: |
#        python -m cookiecutter
#    - name: Test project
    - name: CI finished
      run: |
        echo CI pipeline finished